// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Vigil.Infrastructure.Persistence;

#nullable disable

namespace Vigil.Infrastructure.Migrations
{
    [DbContext(typeof(VigilDbContext))]
    [Migration("20260819202747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vigil.Core.Domain.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStep")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("analysis_jobs", (string)null);
                });

            modelBuilder.Entity("Vigil.Core.Domain.AnalysisReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceTrail")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("MitreTechniques")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RecommendedActions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SummaryMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("RiskScore");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("Vigil.Core.Domain.CloudtrailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AwsRegion")
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawEvent")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceIp")
                        .HasColumnType("text");

                    b.Property<string>("UserIdentity")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventTime");

                    b.HasIndex("SourceIp");

                    b.ToTable("cloudtrail_logs", (string)null);
                });

            modelBuilder.Entity("Vigil.Core.Domain.IncidentEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(384)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("incident_embeddings", (string)null);
                });

            modelBuilder.Entity("Vigil.Core.Domain.Ioc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExtractedBy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Type", "Value");

                    b.ToTable("iocs", (string)null);
                });

            modelBuilder.Entity("Vigil.Core.Domain.ThreatIntelResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("FromLiveApi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IocId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LookedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MaliciousScore")
                        .HasColumnType("double precision");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IocId");

                    b.HasIndex("LookedUpAt");

                    b.ToTable("threat_intel_results", (string)null);
                });

            modelBuilder.Entity("Vigil.Core.Domain.Tier1Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<double?>("MlScore")
                        .HasColumnType("double precision");

                    b.Property<string>("RuleCheckResults")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ScrubbedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("tier1_results", (string)null);
                });

            modelBuilder.Entity("Vigil.Core.Domain.AnalysisReport", b =>
                {
                    b.HasOne("Vigil.Core.Domain.AnalysisJob", "Job")
                        .WithOne("Report")
                        .HasForeignKey("Vigil.Core.Domain.AnalysisReport", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Vigil.Core.Domain.IncidentEmbedding", b =>
                {
                    b.HasOne("Vigil.Core.Domain.AnalysisReport", "Report")
                        .WithOne("Embedding")
                        .HasForeignKey("Vigil.Core.Domain.IncidentEmbedding", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Vigil.Core.Domain.Ioc", b =>
                {
                    b.HasOne("Vigil.Core.Domain.AnalysisJob", "Job")
                        .WithMany("Iocs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Vigil.Core.Domain.ThreatIntelResult", b =>
                {
                    b.HasOne("Vigil.Core.Domain.Ioc", "Ioc")
                        .WithMany("IntelResults")
                        .HasForeignKey("IocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ioc");
                });

            modelBuilder.Entity("Vigil.Core.Domain.Tier1Result", b =>
                {
                    b.HasOne("Vigil.Core.Domain.AnalysisJob", "Job")
                        .WithOne("Tier1Result")
                        .HasForeignKey("Vigil.Core.Domain.Tier1Result", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Vigil.Core.Domain.AnalysisJob", b =>
                {
                    b.Navigation("Iocs");

                    b.Navigation("Report");

                    b.Navigation("Tier1Result");
                });

            modelBuilder.Entity("Vigil.Core.Domain.AnalysisReport", b =>
                {
                    b.Navigation("Embedding");
                });

            modelBuilder.Entity("Vigil.Core.Domain.Ioc", b =>
                {
                    b.Navigation("IntelResults");
                });
#pragma warning restore 612, 618
        }
    }
}
