using System.Text.Json;
using Microsoft.Extensions.Logging.Abstractions;
using Vigil.Infrastructure.Ml;

namespace Vigil.IntegrationTests;

/// <summary>
/// Parity between the C# <see cref="OnnxEmbeddingService"/> and Python
/// sentence-transformers for sentence-transformers/all-MiniLM-L6-v2. The
/// fixture (tests/fixtures/embedding_baseline.json) was generated by
/// tools/export_embedding_onnx.py and carries, per sentence, the ST tokenizer's
/// input ids and the ST embedding, plus pairwise cosine similarities.
///
/// The tests skip (not fail) when models/minilm.onnx has not been exported
/// yet — run tools/export_embedding_onnx.py once in the Python venv.
/// </summary>
public class EmbeddingParityTests
{
    /// <summary>Per-sentence cosine similarity between C# and Python embeddings.</summary>
    private const double MinCosine = 0.999;

    /// <summary>Max divergence of pairwise cosine similarities, as required by the plan.</summary>
    private const double PairwiseTolerance = 0.02;

    private static readonly string RepoRoot = FindRepoRoot();

    [SkippableFact]
    public async Task CSharp_token_ids_match_sentence_transformers()
    {
        Skip.IfNot(File.Exists(ModelPath),
            "models/minilm.onnx missing — run tools/export_embedding_onnx.py in the Python venv first.");

        var fixture = await LoadFixtureAsync();
        using var service = CreateService();

        Assert.Equal(OnnxEmbeddingService.MaxTokenCount, fixture.MaxTokens);

        foreach (var entry in fixture.Entries)
        {
            var ids = service.EncodeIds(entry.Text);
            Assert.True(ids.SequenceEqual(entry.InputIds),
                $"C# token ids diverge from sentence-transformers for: {entry.Text[..Math.Min(60, entry.Text.Length)]}");
        }
    }

    [SkippableFact]
    public async Task CSharp_embeddings_match_sentence_transformers()
    {
        Skip.IfNot(File.Exists(ModelPath),
            "models/minilm.onnx missing — run tools/export_embedding_onnx.py in the Python venv first.");

        var fixture = await LoadFixtureAsync();
        using var service = CreateService();

        var csharpEmbeddings = new float[fixture.Entries.Count][];
        for (var i = 0; i < fixture.Entries.Count; i++)
        {
            var entry = fixture.Entries[i];
            var embedding = await service.EmbedAsync(entry.Text);
            Assert.NotNull(embedding);
            Assert.Equal(OnnxEmbeddingService.HiddenSize, embedding!.Length);

            var cosine = CosineSimilarity(embedding, entry.Embedding);
            Assert.True(cosine >= MinCosine,
                $"Entry {i}: C# vs Python cosine similarity {cosine:F6} < {MinCosine}.");
            csharpEmbeddings[i] = embedding;
        }

        // Pairwise cosine similarity parity (the RAG ranking signal).
        foreach (var pair in fixture.Pairs)
        {
            var csharp = CosineSimilarity(csharpEmbeddings[pair.A], csharpEmbeddings[pair.B]);
            Assert.True(Math.Abs(csharp - pair.Cosine) <= PairwiseTolerance,
                $"Pair ({pair.A},{pair.B}): C# {csharp:F6} vs Python {pair.Cosine:F6}.");
        }
    }

    private static string ModelPath => Path.Combine(RepoRoot, "models", "minilm.onnx");

    private static string VocabPath => Path.Combine(RepoRoot, "models", "vocab.txt");

    private static OnnxEmbeddingService CreateService() =>
        new(ModelPath, VocabPath, enabled: true, NullLogger<OnnxEmbeddingService>.Instance);

    private static double CosineSimilarity(IReadOnlyList<float> a, IReadOnlyList<float> b)
    {
        double dot = 0, normA = 0, normB = 0;
        for (var i = 0; i < a.Count; i++)
        {
            dot += a[i] * (double)b[i];
            normA += a[i] * (double)a[i];
            normB += b[i] * (double)b[i];
        }

        return dot / (Math.Sqrt(normA) * Math.Sqrt(normB));
    }

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Vigil.sln")))
        {
            dir = dir.Parent;
        }

        return dir?.FullName
            ?? throw new InvalidOperationException("Could not locate the repository root (Vigil.sln).");
    }

    private static async Task<EmbeddingFixture> LoadFixtureAsync()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "fixtures", "embedding_baseline.json");
        await using var stream = File.OpenRead(path);
        return await JsonSerializer.DeserializeAsync<EmbeddingFixture>(stream,
                   new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
            ?? throw new InvalidOperationException("embedding_baseline.json is empty or malformed.");
    }

    private sealed record EmbeddingFixture(
        int MaxTokens, int Dimensions, List<FixtureEntry> Entries, List<FixturePair> Pairs);

    private sealed record FixtureEntry(string Text, List<int> InputIds, float[] Embedding);

    private sealed record FixturePair(int A, int B, double Cosine);
}
