using System.Text.Json;
using Microsoft.Extensions.Logging.Abstractions;
using Vigil.Core.Security;
using Vigil.Core.Tier1;
using Vigil.Infrastructure.Ml;
using Xunit;

namespace Vigil.IntegrationTests;

/// <summary>
/// Parity between the C# ONNX classifier and the original Python pipeline
/// (bastion/models/ml_models.py) on every dataset .eml. The baseline fixture
/// (tests/fixtures/ml_baseline.json) was generated by tools/export_onnx.py with
/// the HuggingFace model; each entry carries the HF tokenizer's input ids, the
/// phishing probability and the 0.7-threshold verdict.
///
/// The tests skip (not fail) when models/phishing.onnx has not been exported
/// yet — run tools/export_onnx.py once in the Python venv to produce it.
/// </summary>
public class MlParityTests
{
    private const double Tolerance = 0.01;

    private static readonly string RepoRoot = FindRepoRoot();

    [SkippableFact]
    public async Task CSharp_scores_match_python_baseline_within_tolerance()
    {
        Skip.IfNot(File.Exists(ModelPath),
            "models/phishing.onnx missing — run tools/export_onnx.py in the Python venv first.");

        var baseline = await LoadBaselineAsync();
        Assert.Equal(7, baseline.Entries.Count);

        using var classifier = new PhishingClassifier(
            ModelPath, VocabPath, baseline.Threshold, enabled: true,
            NullLogger<PhishingClassifier>.Instance);

        foreach (var entry in baseline.Entries)
        {
            // Same extraction the Worker pipeline applies: scrub, parse, combine.
            var raw = await File.ReadAllTextAsync(
                Path.Combine(AppContext.BaseDirectory, "fixtures", entry.File));
            var message = EmlParser.Parse(PiiScrubber.Scrub(raw));

            var ids = classifier.EncodeIds(message.Subject, message.Body);
            Assert.True(ids.SequenceEqual(entry.InputIds),
                $"{entry.File}: C# token ids diverge from the HuggingFace tokenizer.");

            var score = classifier.Classify(message.Subject, message.Body);
            Assert.True(Math.Abs(score - entry.PhishingScore) <= Tolerance,
                $"{entry.File}: C# score {score:F6} vs Python {entry.PhishingScore:F6}.");

            // Verdict parity at the configured threshold (0.7).
            Assert.Equal(entry.Suspicious, score >= classifier.Threshold);
        }
    }

    private static string ModelPath => Path.Combine(RepoRoot, "models", "phishing.onnx");

    private static string VocabPath => Path.Combine(RepoRoot, "models", "vocab.txt");

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Vigil.sln")))
        {
            dir = dir.Parent;
        }

        return dir?.FullName
            ?? throw new InvalidOperationException("Could not locate the repository root (Vigil.sln).");
    }

    private static async Task<MlBaseline> LoadBaselineAsync()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "fixtures", "ml_baseline.json");
        await using var stream = File.OpenRead(path);
        return await JsonSerializer.DeserializeAsync<MlBaseline>(stream,
                   new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
            ?? throw new InvalidOperationException("ml_baseline.json is empty or malformed.");
    }

    private sealed record MlBaseline(double Threshold, List<BaselineEntry> Entries);

    private sealed record BaselineEntry(
        string File, string Subject, double PhishingScore, bool Suspicious, List<int> InputIds);
}
